# Generated by Django 4.1.7 on 2023-02-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='ФИО')),
                ('boy_age', models.CharField(max_length=50, verbose_name='18')),
                ('score', models.CharField(max_length=50, verbose_name='10')),
                ('task', models.TextField(verbose_name='проступок')),
            ],
        ),
    ]
