# Generated by Django 4.1.7 on 2023-05-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_tasks_score_remove_tasks_task_tasks_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='score',
            field=models.CharField(default='0', max_length=50, verbose_name='10'),
        ),
    ]
